using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ZeroGameStudio.ConfigPipeline.Editor
{
    public static class ConfigCodeGenerator
    {
        public static byte[] Generate(
            ConfigSchema schema,
            string generatedNamespace,
            string rootClassName,
            string contractClassName)
        {
            if (schema == null)
            {
                throw new ArgumentNullException(nameof(schema));
            }

            ValidateIdentifier(generatedNamespace, nameof(generatedNamespace), true);
            ValidateIdentifier(rootClassName, nameof(rootClassName), false);
            ValidateIdentifier(contractClassName, nameof(contractClassName), false);
            var definitions = new List<ClassDefinition>();
            BuildObjectDefinition(schema.Root, rootClassName, definitions);

            var builder = new StringBuilder();
            builder.Append("// <auto-generated />\n");
            builder.Append("using System.Collections.Generic;\n\n");
            builder.Append("namespace ").Append(generatedNamespace).Append("\n{\n");
            builder.Append("    public static class ").Append(contractClassName).Append("\n    {\n");
            builder.Append("        public const string SchemaId = \"")
                .Append(EscapeString(schema.SchemaId)).Append("\";\n");
            builder.Append("        public const int SchemaVersion = ")
                .Append(schema.SchemaVersion).Append(";\n");
            builder.Append("        public const string SchemaHash = \"")
                .Append(schema.SchemaHash).Append("\";\n");
            builder.Append("    }\n");

            foreach (ClassDefinition definition in definitions)
            {
                builder.Append("\n    public sealed class ")
                    .Append(definition.Name)
                    .Append("\n    {\n");
                foreach (FieldDefinition field in definition.Fields)
                {
                    builder.Append("        [Newtonsoft.Json.JsonProperty(\"")
                        .Append(EscapeString(field.JsonName))
                        .Append("\")]\n");
                    builder.Append("        public ")
                        .Append(field.TypeName)
                        .Append(' ')
                        .Append(field.FieldName)
                        .Append(";\n\n");
                }

                builder.Append("    }\n");
            }

            builder.Append("}\n");
            return new UTF8Encoding(false, true).GetBytes(builder.ToString());
        }

        private static string BuildObjectDefinition(
            ConfigSchemaNode schema,
            string className,
            List<ClassDefinition> definitions)
        {
            var fields = new List<FieldDefinition>();
            foreach (ConfigSchemaProperty property in schema.Properties)
            {
                if (property.Schema.AuthoringOnly)
                {
                    continue;
                }

                string fieldName = ToIdentifier(property.Name, true);
                string typeName = ResolveType(
                    property.Schema,
                    className + ToIdentifier(property.Name, true),
                    definitions);
                fields.Add(new FieldDefinition(property.Name, fieldName, typeName));
            }

            definitions.Add(new ClassDefinition(className, fields));
            return className;
        }

        private static string ResolveType(
            ConfigSchemaNode schema,
            string suggestedName,
            List<ClassDefinition> definitions)
        {
            switch (schema.Type)
            {
                case ConfigSchemaType.Boolean:
                    return "bool";
                case ConfigSchemaType.String:
                    return "string";
                case ConfigSchemaType.Integer:
                    return schema.IntegerType == ConfigIntegerType.Int32 ? "int" : "long";
                case ConfigSchemaType.Number:
                    return schema.NumberType == ConfigNumberType.Float32 ? "float" : "double";
                case ConfigSchemaType.Object:
                    return BuildObjectDefinition(schema, suggestedName + "Dto", definitions);
                case ConfigSchemaType.Array:
                    return "List<" +
                           ResolveType(schema.Items, suggestedName + "Item", definitions) +
                           ">";
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        private static string ToIdentifier(string value, bool pascalCase)
        {
            var builder = new StringBuilder();
            bool capitalize = pascalCase;
            foreach (char character in value)
            {
                if (!char.IsLetterOrDigit(character) && character != '_')
                {
                    capitalize = true;
                    continue;
                }

                char next = capitalize ? char.ToUpperInvariant(character) : character;
                if (builder.Length == 0 && !char.IsLetter(next) && next != '_')
                {
                    builder.Append('_');
                }

                builder.Append(next);
                capitalize = false;
            }

            if (builder.Length == 0)
            {
                throw new ArgumentException("Schema field cannot map to an empty C# identifier.");
            }

            return builder.ToString();
        }

        private static void ValidateIdentifier(string value, string parameterName, bool allowDots)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new ArgumentException("C# identifier is required.", parameterName);
            }

            string[] segments = allowDots ? value.Split('.') : new[] { value };
            if (segments.Any(segment =>
                    segment.Length == 0 ||
                    (!char.IsLetter(segment[0]) && segment[0] != '_') ||
                    segment.Skip(1).Any(character =>
                        !char.IsLetterOrDigit(character) && character != '_')))
            {
                throw new ArgumentException("Invalid C# identifier.", parameterName);
            }
        }

        private static string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private sealed class ClassDefinition
        {
            public ClassDefinition(string name, IReadOnlyList<FieldDefinition> fields)
            {
                Name = name;
                Fields = fields;
            }

            public string Name { get; }

            public IReadOnlyList<FieldDefinition> Fields { get; }
        }

        private sealed class FieldDefinition
        {
            public FieldDefinition(string jsonName, string fieldName, string typeName)
            {
                JsonName = jsonName;
                FieldName = fieldName;
                TypeName = typeName;
            }

            public string JsonName { get; }

            public string FieldName { get; }

            public string TypeName { get; }
        }
    }
}
